package SubGUI;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import model.Numbers;
import javax.swing.table.DefaultTableCellRenderer;
import model.MySQL;

/**
 *
 * @author Sandeep
 */
public class InvoiceDetails extends javax.swing.JFrame {

    //Inisilize Varables
    private String invoiceId;

    public InvoiceDetails(String invoiceId) {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resource/icon.png")));
        initComponents();
        this.invoiceId = invoiceId;
        loadInvoiceData();
    }

    private void loadInvoiceData() {
        try {

            ResultSet invoiceResultSet = MySQL.execute("SELECT * FROM invoice i "
                    + "INNER JOIN payment_method pm ON i.payment_method_id = pm.id "
                    + "WHERE i.invoice_id = '" + invoiceId + "' ");

            if (invoiceResultSet.next()) {
                DefaultTableModel model = (DefaultTableModel) invoiceItemsTable.getModel();
                model.setRowCount(0);

                //Load Invoice Data
                invoiceIdLabel.setText(invoiceResultSet.getString("invoice_id"));
                invoiceDataLabel.setText(""
                        + "Date Time : " + invoiceResultSet.getString("i.invoice_id") + "          "
                        + "Item Count : " + invoiceResultSet.getString("i.item_count") + "          "
                        + "Payment Method : " + invoiceResultSet.getString("pm.name") + "");

                invoiceAmountLabel.setText(Numbers.formatPrice(invoiceResultSet.getDouble("i.total_amount")));
                discountValueLabel.setText(Numbers.formatPrice(invoiceResultSet.getDouble("i.discount")));
                netTotalValueLabel.setText(Numbers.formatPrice(invoiceResultSet.getDouble("i.net_total")));
                returnPaymentValueLabel.setText(Numbers.formatPrice(invoiceResultSet.getDouble("i.return_payment_amount")));
                payableValueLabel.setText(Numbers.formatPrice(invoiceResultSet.getDouble("i.payable_amount")));
                paidAmountValueLabel.setText(Numbers.formatPrice(invoiceResultSet.getDouble("i.paid_amount")));
                balanceValueLabel.setText(Numbers.formatPrice(invoiceResultSet.getDouble("i.balance")));

                //Load Invoice Items
                ResultSet itemsResultSet = MySQL.execute("SELECT * FROM invoice_item ii "
                        + "INNER JOIN stock s ON ii.stock_barcode = s.barcode "
                        + "INNER JOIN product p ON s.product_id = p.id "
                        + "INNER JOIN measurement_unit mu ON p.measurement_unit_id = mu.id "
                        + "WHERE ii.invoice_id = '" + invoiceId + "' ");

                int rowCount = invoiceItemsTable.getRowCount();

                while (itemsResultSet.next()) {
                    Vector v = new Vector();
                    v.add(rowCount + 1);
                    v.add(itemsResultSet.getString("ii.stock_barcode"));
                    v.add(itemsResultSet.getString("p.name"));
                    v.add(Numbers.formatPrice(itemsResultSet.getDouble("ii.marked_price")));
                    v.add(Numbers.formatPrice(itemsResultSet.getDouble("ii.selling_discount")));
                    v.add(Numbers.formatPrice(itemsResultSet.getDouble("ii.selling_price")));
                    v.add(Numbers.formatQuantity(itemsResultSet.getDouble("ii.quantity")));
                    v.add(itemsResultSet.getString("mu.name"));
                    v.add(Numbers.formatPrice(itemsResultSet.getDouble("ii.item_amount")));
                    rowCount++;
                    model.addRow(v);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Invalid invoice ID", "Warning", JOptionPane.WARNING_MESSAGE);

            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An unexpected error has occurred. Please try again later or contact support if the issue persists.", "Unexpected Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        timePicker = new com.raven.swing.TimePicker();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        invoiceIdLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        invoiceDataLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel22 = new javax.swing.JPanel();
        invoiceAmountLabel = new javax.swing.JLabel();
        discountValueLabel = new javax.swing.JLabel();
        netTotalValueLabel = new javax.swing.JLabel();
        netTotalTextLabel4 = new javax.swing.JLabel();
        discountTextLabel4 = new javax.swing.JLabel();
        totalTextLabel4 = new javax.swing.JLabel();
        netTotalTextLabel5 = new javax.swing.JLabel();
        paidAmountValueLabel = new javax.swing.JLabel();
        netTotalTextLabel6 = new javax.swing.JLabel();
        balanceValueLabel = new javax.swing.JLabel();
        netTotalTextLabel7 = new javax.swing.JLabel();
        returnPaymentValueLabel = new javax.swing.JLabel();
        netTotalTextLabel8 = new javax.swing.JLabel();
        payableValueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceItemsTable = new javax.swing.JTable();
        jPanel23 = new javax.swing.JPanel();
        saveButton5 = new javax.swing.JButton();
        PayButton1 = new javax.swing.JButton();
        saveAndPrintButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        supplierNameShowLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        dateChooser.setForeground(new java.awt.Color(0, 105, 75));
        dateChooser.setDateFormat("yyyy-MM-dd");

        timePicker.setForeground(new java.awt.Color(0, 105, 75));
        timePicker.set24hourMode(true);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INVOICE");
        setMinimumSize(new java.awt.Dimension(1090, 696));

        invoiceIdLabel.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        invoiceIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        invoiceIdLabel.setText("INV0000017");
        invoiceIdLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 30));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel3.setText("INVOICE");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));

        invoiceDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invoiceDataLabel.setText("Date Time : 2024-10-12 10:24:00          Item Count : 12 Items          Payment Method : Not Paid");
        invoiceDataLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        invoiceAmountLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        invoiceAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        invoiceAmountLabel.setText("0.00");

        discountValueLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        discountValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        discountValueLabel.setText("0.00");

        netTotalValueLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        netTotalValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        netTotalValueLabel.setText("0.00");

        netTotalTextLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        netTotalTextLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        netTotalTextLabel4.setText("Net Total (Rs.) :");

        discountTextLabel4.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        discountTextLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        discountTextLabel4.setText("Disount (Rs.) :");

        totalTextLabel4.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        totalTextLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalTextLabel4.setText("Invoice Amount (Rs.) :");

        netTotalTextLabel5.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        netTotalTextLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        netTotalTextLabel5.setText("Paid Amont (Rs.) :");

        paidAmountValueLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        paidAmountValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paidAmountValueLabel.setText("0.00");

        netTotalTextLabel6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        netTotalTextLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        netTotalTextLabel6.setText("Balance (Rs.) :");

        balanceValueLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        balanceValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        balanceValueLabel.setText("0.00");

        netTotalTextLabel7.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        netTotalTextLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        netTotalTextLabel7.setText("Return Payment (Rs.) :");

        returnPaymentValueLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        returnPaymentValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        returnPaymentValueLabel.setText("0.00");

        netTotalTextLabel8.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        netTotalTextLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        netTotalTextLabel8.setText("Payable Amount (Rs.) :");

        payableValueLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        payableValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        payableValueLabel.setText("0.00");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discountTextLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(netTotalTextLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discountValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netTotalValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addComponent(totalTextLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invoiceAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addComponent(netTotalTextLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paidAmountValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(netTotalTextLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balanceValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addComponent(netTotalTextLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnPaymentValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addComponent(netTotalTextLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(payableValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTextLabel4)
                    .addComponent(invoiceAmountLabel))
                .addGap(0, 0, 0)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addComponent(discountTextLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(netTotalTextLabel4))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(discountValueLabel)
                        .addGap(0, 0, 0)
                        .addComponent(netTotalValueLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(netTotalTextLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(returnPaymentValueLabel))
                .addGap(0, 0, 0)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(netTotalTextLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(payableValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(netTotalTextLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paidAmountValueLabel))
                .addGap(0, 0, 0)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(netTotalTextLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(balanceValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        invoiceItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Stock Barcode", "Product Name", "Marked Price", "Discount", "Selling Price", "Quantity", "Measurement Unit", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        invoiceItemsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        invoiceItemsTable.getTableHeader().setReorderingAllowed(false);

        // Center-align the first column (index 0)
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        invoiceItemsTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        invoiceItemsTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        invoiceItemsTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        invoiceItemsTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        invoiceItemsTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        invoiceItemsTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        invoiceItemsTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        invoiceItemsTable.getColumnModel().getColumn(7).setCellRenderer(centerRenderer);

        // Right-align the second column (index 1)
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        invoiceItemsTable.getColumnModel().getColumn(8).setCellRenderer(rightRenderer);
        invoiceItemsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceItemsTableMouseClicked(evt);
            }
        });
        invoiceItemsTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invoiceItemsTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(invoiceItemsTable);

        saveButton5.setText("View Returned Items");
        saveButton5.setToolTipText("Add New Product");
        saveButton5.setBorder(null);
        saveButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton5ActionPerformed(evt);
            }
        });

        PayButton1.setText("Return Items");
        PayButton1.setToolTipText("Add New Product");
        PayButton1.setBorder(null);
        PayButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButton1ActionPerformed(evt);
            }
        });

        saveAndPrintButton4.setText("Print Invoice");
        saveAndPrintButton4.setToolTipText("Add New Product");
        saveAndPrintButton4.setBorder(null);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PayButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveAndPrintButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveAndPrintButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PayButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invoiceDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invoiceIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invoiceIdLabel)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(invoiceDataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 0, 0, 0));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 105, 75));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logo-extra-sm.png"))); // NOI18N
        jLabel2.setIconTextGap(20);
        jPanel9.add(jLabel2);

        supplierNameShowLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supplierNameShowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supplierNameShowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.add(jPanel18);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu2.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Select Stock");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void invoiceItemsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceItemsTableMouseClicked

        if (evt.getClickCount() == 2) {
            int selectedRow = invoiceItemsTable.getSelectedRow();

            if (selectedRow != -1) {
//                setStock(String.valueOf(invoiceItemsTable.getValueAt(selectedRow, 1)));
            }
        }
    }//GEN-LAST:event_invoiceItemsTableMouseClicked

    private void invoiceItemsTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceItemsTableKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceItemsTableKeyReleased

    private void saveButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButton5ActionPerformed

    private void PayButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PayButton1;
    private javax.swing.JLabel balanceValueLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JLabel discountTextLabel4;
    private javax.swing.JLabel discountValueLabel;
    private javax.swing.JLabel invoiceAmountLabel;
    private javax.swing.JLabel invoiceDataLabel;
    private javax.swing.JLabel invoiceIdLabel;
    private javax.swing.JTable invoiceItemsTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel netTotalTextLabel4;
    private javax.swing.JLabel netTotalTextLabel5;
    private javax.swing.JLabel netTotalTextLabel6;
    private javax.swing.JLabel netTotalTextLabel7;
    private javax.swing.JLabel netTotalTextLabel8;
    private javax.swing.JLabel netTotalValueLabel;
    private javax.swing.JLabel paidAmountValueLabel;
    private javax.swing.JLabel payableValueLabel;
    private javax.swing.JLabel returnPaymentValueLabel;
    private javax.swing.JButton saveAndPrintButton4;
    private javax.swing.JButton saveButton5;
    private javax.swing.JLabel supplierNameShowLabel;
    private com.raven.swing.TimePicker timePicker;
    private javax.swing.JLabel totalTextLabel4;
    // End of variables declaration//GEN-END:variables
}
